### ISSUE TITLE
Not able to run API server!

### ISSUE THREAD

**Issue by amandeepmittal** [EQuimper/keepmyfolio#4]
Hi, I am not able to run API server. I get the following error:

![screen shot 2018-08-12 at 12 50 02 am](https://user-images.githubusercontent.com/10234615/43995348-c0d1f882-9dc9-11e8-9117-0956c935f2c8.png)

Can you suggest how to run it?

**Comment by EQuimper** [comment]
Did you install the serverless framework cli ?

**Comment by EQuimper** [comment]
http://serverless.com/

**Comment by amandeepmittal** [comment]
Thanks!
